// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfmeitgutgaagflcpcdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbWVpdGd1dGdhYWdmbGNwY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjYxMzgsImV4cCI6MjA3MjUwMjEzOH0.UYKMs3qczRdEuVFb1i9mM1qgh-f-Y3C32E5iL6eyMzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});